### ISSUE TITLE
Adding a callback function for when the list is exhausted

### ISSUE THREAD

**Issue by MicJarek** [zeshanshani/simple-load-more#11]
Is there a way to implement a Callback function when the list is completely shown (and the ‘More’ button is hidden)? Meaning, when the last items are displayed to the user, is there a way that I can detect that and trigger a function of my own to do additional processing.

What I’m trying to do is get the next set of records from the database (via AJAX) so the user can ‘transparently’ continue viewing them, until all the records are exhausted.

BTW: I have implemented simple-load-more throughout the app and it works great! I think adding this little feature will make it a more robust tool since it will then not be limited to just the initial retrieve/list display.

**Comment by zeshanshani** [comment]
@MicJarek another great suggestion! 

I will implement this during the next week.

**Comment by zeshanshani** [comment]
@MicJarek this feature has been implemented! 

We have three callbacks now:

- `onLoad` fires when instance is fully loaded
- `onNextLoad` fires every time next batch of items are laoded
- `onComplete` fires when all items are loaded

For more details, check out README file: https://github.com/zeshanshani/simple-load-more and view our demo.

**Comment by MicJarek** [comment]
> * `onLoad` fires when instance is fully loaded
> * `onNextLoad` fires every time next batch of items are laoded
> * `onComplete` fires when all items are loaded
 
That's perfect @zeshanshani. The onComplete works great. Tks... :)
