### ISSUE TITLE
Count element showed/total and count view more clicks

### ISSUE THREAD

**Issue by kant1983** [zeshanshani/simple-load-more#3]
I was asking if there was the possibility to insert, first of the button "View More", the number of current elements showed / number of total elements. It would be great if after click on View More the counter of current news was updated. I make a simple example. If I have this configuration, with 50 elements:
count: 10,  itemsToLoad: 5 

<li>Item 1</li>
<li>Item 2</li>
<li>Item 3</li>
<li>Item 4</li>
<li>Item 5</li>
<li>Item 6</li>
<li>Item 7</li>
<li>Item 8</li>
<li>Item 9</li>
<li>Item 10</li>

Number of news: 10/50 
View more >

After the click of the button view more the elements will be 15 and the counter of the current elements will be 15/50 until to get all the elements. Another appreciate issue would be the number of clicks, before View More button until to get the end of elements. In the previous example, given a total of 50 elements, starting with 10 and increasing of 5 elements each time, it should be so:

Number of news: 10/50
[-8] View more >

After the click of "View more" button, the counter of clicks decrease until to get -1, when it arrives to 0 it means we have showed all the elements and so both counter click and view more button is not showed.

**Comment by zeshanshani** [comment]
Hi @kant1983,

This is ready in version 1.4.0. Read [options](https://github.com/zeshanshani/simple-load-more#options) to learn more about it. View [demo](https://zeshanshani.github.io/simple-load-more/demos/demo.html) for the examples. 

Thanks,
Zeshan
