### ISSUE TITLE
Customize how the list is displayed

### ISSUE THREAD

**Issue by MicJarek** [zeshanshani/simple-load-more#4]
Great little plugin. Light-weight, easy to implement, and works like a charm. The only thing missing is a custom variable to set how the next list of items will be displayed. Currently clicking the 'Next' button uses fadeIn(), but an option to allow for i.e. slideDown() would be a great addition.

**Comment by zeshanshani** [comment]
@MicJarek thanks for creating this ticket. This feature has been implemented and you can achieve this by setting the option 'easing' to 'slide'.
