### ISSUE TITLE
Ability to wrap HTML around the 'MORE' button

### ISSUE THREAD

**Issue by zeshanshani** [zeshanshani/simple-load-more#5]
Opening this thread on request of @MicJarek

I will be creating a new option using which you can wrap the 'MORE' button in HTML. The purpose is to allow users to apply custom classes and styles on the button. E.g., horizontally centering the button

**Comment by zeshanshani** [comment]
Closing as implemented with #6

**Comment by veerack** [comment]
may i ask how that works? i'm trying to center the view more btnHtml

**Comment by MicJarek** [comment]
@Daishiky the JavaScript code is straight forward:
```
$('.ListResult').simpleLoadMore({
  item: 'div.ListResultItem',
  count: 20,
  itemsToLoad: 20,
  counterInBtn: false,
  btnHTML: '<a class="btn btn-sm btn-outline-primary lp-btn-primary-semi-transparent rounded-pill shadow-none" href="javascript:void(0);"><span class="pl-3 pr-3">More</span></a>',
  btnWrapper: '<div class="lp-btn-load-more-gradient ml-n3 mr-n3"></div>',
  easing: 'slide'
});
```

And the CSS lp-btn-load-more-gradient in defined as:
```
.lp-btn-load-more-gradient {
    position: relative;
    z-index: 999;
    background: rgb(251,251,251);
    background: linear-gradient(0deg, rgba(251,251,251,1) 40%, rgba(251,251,251,0.75) 80%, rgba(251,251,251,0) 100%);
    background-position: center top;
    margin-top: -60px;
    padding-top: 80px;
    top: -10px;
    text-align: center;
}
```
And to get this to display/work in HTML, simply put your items in the div.ListResultItem section, as so:

```
<div class="ListResult">
  <div class="row">
    <div class="container-fluid">
      <div class="col-12">
        <div class="container-fluid ListResultItem">
           {your content item1 go here}
 	</div>
        <div class="container-fluid ListResultItem">
           {your content item2 go here}
 	</div>
        <div class="container-fluid ListResultItem">
           {your content item3 go here}
 	</div>
          .
          .
          .
      </div>
    </div>
  </div>
</div>

```

NOTE: I'm using ASP.NET Core Razor Pages with Bootstrap 4. Also, the class code above produces a nice gradient overlay under the button to encourage the user to click the 'More' button (see image below).

Hope this helps... :)
![image](https://user-images.githubusercontent.com/17038597/135668280-743e7b57-582d-4a9f-ab3e-85e6ec098de7.png)
