### ISSUE TITLE
Bottom Center btnHtml

### ISSUE THREAD

**Issue by veerack** [zeshanshani/simple-load-more#8]
I'm trying to position the `btnHtml` on bottom center with TailwindCSS but without success, here's the code
```html
  <script>
$('.gallery').simpleLoadMore({
  item: 'div',
  count: 180,
  btnHTML: `<a href="#" class="load-more__btn rounded-2xl bg-white text-red-500 px-5 p-2 font-bold mx-auto">View More <i class="fas fa-angle-down"></i></a>`,
});
  </script>
```
Result:
![image](https://user-images.githubusercontent.com/77997662/135619753-fc13b882-46e2-44e4-be4e-f158c1f27f74.png)

**Comment by zeshanshani** [comment]
@Daishiky you need to set the centering classes to another option called `btnWrapperClass `. Please see the options here to learn more about it: https://github.com/zeshanshani/simple-load-more#options

If I modify your code to center the button, this should do the trick:

``` HTML
<script>
$('.gallery').simpleLoadMore({
  item: 'div',
  count: 180,
  btnWrapperClass: 'text-center',
  btnHTML: `<a href="#" class="load-more__btn rounded-2xl bg-white text-red-500 px-5 p-2 font-bold">View More <i class="fas fa-angle-down"></i></a>`,
});
  </script>
```

the `text-center` class will work if you are using Bootstrap. Otherwise, use a CSS class that does `text-align: center`

Hope this helps

**Comment by veerack** [comment]
> @Daishiky you need to set the centering classes to another option called `btnWrapperClass `. Please see the options here to learn more about it: https://github.com/zeshanshani/simple-load-more#options
> 
> If I modify your code to center the button, this should do the trick:
> 
> ```
> <script>
> $('.gallery').simpleLoadMore({
>   item: 'div',
>   count: 180,
>   btnWrapperClass: 'text-center',
>   btnHTML: `<a href="#" class="load-more__btn rounded-2xl bg-white text-red-500 px-5 p-2 font-bold">View More <i class="fas fa-angle-down"></i></a>`,
> });
>   </script>
> ```
> 
> the `text-center` class will work if you are using Bootstrap. Otherwise, use a CSS class that does `text-align: center`
> 
> Hope this helps

i tried but the button still goes under the last element in the div :/
![image](https://user-images.githubusercontent.com/77997662/136671929-b7c18c1f-7096-4a17-a2cc-a2888ea8cf71.png)

**Comment by zeshanshani** [comment]
@Daishiky I see that the button is centered but width is set same as the last element. 

Can you send a link where this is so I can see what could be wrong here?
