### ISSUE TITLE
Update or Refresh callback

### ISSUE THREAD

**Issue by BenGenPub** [zeshanshani/simple-load-more#9]
Can we have an update or refresh callback if, for instance, we are sorting through a list and are removing/hiding some items?

**Comment by zeshanshani** [comment]
@BenGenPub this plugin was made for simple usage so no callbacks were created. But it makes sense now since it's been used by thousands of users. 

I'll look into it and release an update hopefully soon.

**Comment by BenGenPub** [comment]
Quick response!  Kudos on a great plugin; small, lightweight, easy to use!  And glad to see a quick response from the developer!

**Comment by zeshanshani** [comment]
@BenGenPub thank you! :)

And thank you for opening this issue. It will for sure be a nice feature to this plugin.

**Comment by zeshanshani** [comment]
@BenGenPub this feature has been implemented! 

We have three callbacks now:

- `onLoad` fires when instance is fully loaded
- `onNextLoad` fires every time next batch of items are laoded
- `onComplete` fires when all items are loaded

For more details, check out README file: https://github.com/zeshanshani/simple-load-more and view our demo.

**Comment by kelvin-zhao** [comment]
How can we use this callbacks to force simpleLoadMore to re-look at all the divs after we've done some 'filtering'? E.g. if my filtering hides some divs, I need to let simpleLoadMore look at the available divs again to do its magic.
